---
- name: Create the {{ name_prefix }} environment
  hosts: localhost
  gather_facts: False
  vars_files:
    - ['vars/custom.yml', 'vars/main.yml']
  tags:
    - manage-instances
  tasks:
    - include_role:
        name: "check_setup"
      when: not teardown
    - include_role:
        name: "manage-{{ instance_loc }}-instances"

- name: Configure Active Directory Domain Controller
  hosts: windows_domain_controllers
  gather_facts: True
  vars_files:
    - ['vars/custom.yml', 'vars/main.yml']
  tags:
    - windows-ad-controller
  tasks:
    - include_role:
        name: "windows-ad-controller"
      when: provision_windows and not teardown

- name: Configure Windows Servers
  hosts: windows
  gather_facts: True
  vars_files:
    - ['vars/custom.yml', 'vars/main.yml']
  tags:
    - windows_hosts
  tasks:
    - include_role:
        name: windows-common
      when: provision_windows and not teardown

- name: Configure Ansible Tower
  hosts: tower
  become: True
  gather_facts: True
  vars_files:
    - ['vars/custom.yml', 'vars/main.yml']
  tags:
    - ansible-tower
  tasks:
    - include_role:
        name: linux-common
      when: not teardown
    - include_role:
        name: ansible-tower
      when: not teardown

- name: Configure Windows Workstation
  hosts: windows_workstations
  gather_facts: True
  vars_files:
    - ['vars/custom.yml', 'vars/main.yml']
  tags:
    - windows-workstation
  tasks:
    - include_role:
        name: windows-workstation
      when: provision_windows and not teardown and windows_workstation_count > 0
