---
- name: set user fact
  set_fact:
    user: "{{ user_prefix }}"

- block:
  - name: install Chocolatey
    win_chocolatey:
      name: chocolatey
      state: present

  - name: disable enhanced exit codes
    win_chocolatey_feature:
      name: useEnhancedExitCodes
      state: disabled

  - name: Install Chrome
    win_chocolatey:
      name: "{{ item }}"
      ignore_checksums: true
    with_items:
      - googlechrome

  - name: Create an shortcut to Tower site
    win_shortcut:
      src: '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%UserProfile%\Desktop\Ansible Tower.lnk'
      args: --new-window http://{{ name_prefix }}-tower.{{ dns_domain_name }}/
      directory: '%ProgramFiles(x86)%\Google\Chrome\Application'
      icon: '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe,0'

  - name: Create an shortcut to Ansible Docs site
    win_shortcut:
      src: '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe'
      dest: '%UserProfile%\Desktop\Ansible Docs.lnk'
      args: --new-window http://docs.ansible.com/
      directory: '%ProgramFiles(x86)%\Google\Chrome\Application'
      icon: '%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe,0'

  - name: Set Chrome to default Browser
    win_regedit:
      path: HKCU:\Software\Microsoft\Windows\Shell\Associations\UrlAssociations\{{ item }}\UserChoice
      name: ProgId
      data: ChromeHTML
    with_items:
      - http
      - https

  - name: Set Chrome to not ask about default browser
    win_regedit:
      path: HKLM:\Software\Policies\Google\Chrome
      name: DefaultBrowserSettingEnabled
      data: 0
      type: dword

  - name: Disable Chrome Welcome Screen
    win_regedit:
      path: HKLM:\Software\Policies\Google\Chrome
      name: "{{ item }}"
      data: 0
      type: dword
    with_items:
      - PromotionalTabsEnabled
      - WelcomePageOnOSUpgradeEnabled

  - name: Disable Chrome Syncing
    win_regedit:
      path: HKLM:\Software\Policies\Google\Chrome
      name: SyncDisabled
      data: 1
      type: dword

  - name: Disable Server Management at Startup
    win_regedit:
      path: HKCU:\Software\Microsoft\ServerManager\
      name: DoNotOpenServerManagerAtLogon
      data: 1
      type: dword

  - name: Remove EC2 Feedback Icon
    win_file:
      path: C:\Users\{{ user }}\Desktop\EC2 Feedback.website
      state: absent

  - name: Remove EC2 Website Icon
    win_file:
      path: C:\Users\{{ user }}\Desktop\EC2 Microsoft Windows Guide.website
      state: absent

  become: yes
  become_user: "{{ dns_domain_name_short }}\\{{ user }}"
  become_method: runas

- include_tasks: myrtille.yml
