---
- name: grab boto version
  command: python -c 'import boto3; print(boto3.__version__)'
  register: py_cmd

- name: make sure we are running correct boto version
  assert:
    that:
      - py_cmd.stdout is version('1.7', operator='ge')
    msg: "boto3 >= 1.7 is required."

- name: FIND AZ ZONE FOR REGION {{ ec2_region }}
  aws_az_facts:
    region: "{{ ec2_region }}"
  register: az_names

- name: SET AZ ZONE TO FIRST AVAILABLE
  set_fact:
    ec2_az: "{{ az_names.availability_zones[0].zone_name }}"

- name: grab information about AWS user
  aws_caller_facts:
    region: "{{ ec2_region }}"
  register: whoami

- name: save username of AWS user
  set_fact:
    demolab_user: '{{ whoami.arn.split("/")[-1] }}'
