---
- name: DomainController | Obtain windows passwords for instances
  ec2_win_password:
    region: '{{ ec2_region }}'
    instance_id: "{{ item.id }}"
    key_file: "{{ playbook_dir }}/sshkeys/{{ demolab_user }}-{{ name_prefix }}-private.pem"
    wait: yes
    wait_timeout: 45
  with_items: "{{ dc_instances.results | map(attribute='tagged_instances') | list }}"
  register: ec2dc_password
  when: dc_instances is defined

- name: Workstation | Obtain windows passwords for instances
  ec2_win_password:
    region: '{{ ec2_region }}'
    instance_id: "{{ item.id }}"
    key_file: "{{ playbook_dir }}/sshkeys/{{ demolab_user }}-{{ name_prefix }}-private.pem"
    wait: yes
    wait_timeout: 45
  with_items: "{{ workstation_instances.results | map(attribute='tagged_instances') | list }}"
  register: ec2workstation_password
  when: workstation_instances is defined

- name: Windows | Obtain windows passwords for instances
  ec2_win_password:
    region: '{{ ec2_region }}'
    instance_id: "{{ item.id }}"
    key_file: "{{ playbook_dir }}/sshkeys/{{ demolab_user }}-{{ name_prefix }}-private.pem"
    wait: yes
    wait_timeout: 45
  with_items: "{{ windows_instances.results | map(attribute='tagged_instances') | list }}"
  register: ec2windows_password
  when: windows_instances is defined
